import { Button } from "@/components/ui/button";
import { Download, Printer } from "lucide-react";
import { ARCH_BY_ID, CRITERIA, RUBRIC } from "@/data/architectures";
import type { Inputs, RankedResult } from "@/lib/scoring";
import { stageFromMau } from "@/lib/scoring";

interface Props {
  inputs: Inputs;
  results: RankedResult[];
}

function buildMarkdown({ inputs, results }: Props): string {
  const top = results[0];
  const stage = stageFromMau(inputs.mau);
  const lines: string[] = [];

  lines.push(`# Lovable Stack Architect — Architecture Recommendation`);
  lines.push("");
  lines.push(`## Top pick: ${top.arch.name}`);
  lines.push(`_${top.arch.tagline}_`);
  lines.push("");
  lines.push(top.arch.description);
  lines.push("");
  lines.push(`**Why this fits:**`);
  top.rationale.forEach((r) => lines.push(`- ${r}`));
  lines.push("");
  lines.push(`**Estimated cost (${stage}):** ${top.arch.costBands[stage]} / month`);
  lines.push(`**Scaling ceiling:** ${top.arch.scaleCeiling}`);
  lines.push("");

  lines.push(`## Ranked options`);
  results.forEach((r, i) => {
    lines.push(`${i + 1}. **${r.arch.name}** — score ${Math.round(r.score)}/100`);
  });
  lines.push("");

  lines.push(`## Comparison matrix`);
  const header = `| Criterion | ${results.map((r) => r.arch.short).join(" | ")} |`;
  const sep = `| --- | ${results.map(() => "---").join(" | ")} |`;
  lines.push(header);
  lines.push(sep);
  CRITERIA.forEach((c) => {
    lines.push(
      `| ${c.label} | ${results.map((r) => `${RUBRIC[r.arch.id][c.id]}/5`).join(" | ")} |`,
    );
  });
  lines.push("");

  lines.push(`## Project inputs`);
  lines.push(`- Stage: ${inputs.stage}`);
  lines.push(`- Expected MAU: ${inputs.mau.toLocaleString()}`);
  lines.push(`- Team: ${inputs.team.join(", ") || "—"}`);
  lines.push(`- Budget: ${inputs.budget}`);
  lines.push(`- Compliance: ${inputs.compliance.join(", ")}`);
  lines.push(`- Workloads: ${inputs.workloads.join(", ")}`);
  lines.push(`- Lock-in tolerance: ${inputs.lockInTolerance}`);
  lines.push(`- Time-to-market priority: ${inputs.ttmPriority}/5`);
  lines.push("");
  lines.push(`_Generated by Lovable Stack Architect — ${new Date().toLocaleString()}_`);

  return lines.join("\n");
}

export function ReportExport(props: Props) {
  const downloadMd = () => {
    const md = buildMarkdown(props);
    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `lovable-stack-architect-${props.results[0]?.arch.short.toLowerCase() ?? "report"}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="no-print flex flex-wrap gap-2">
      <Button onClick={downloadMd} variant="outline" size="sm" className="gap-1.5">
        <Download className="h-4 w-4" /> Markdown
      </Button>
      <Button onClick={() => window.print()} variant="outline" size="sm" className="gap-1.5">
        <Printer className="h-4 w-4" /> Print / PDF
      </Button>
    </div>
  );
}

// Re-export so the page can also use the markdown if needed.
export { buildMarkdown };
// Suppress unused-import warning for ARCH_BY_ID (kept available for future use).
void ARCH_BY_ID;
